version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app          # локальні файли в контейнер для live reload
      - /app/node_modules      # щоб node_modules не перезаписувався
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true  # щоб dev-server відслідковував зміни у Docker
    command: npm start       # запуск dev-server CRA

  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
    command: npm run dev     # запуск серверу у режимі nodemon або ts-node-dev

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
